# Generated by Django 4.2.7 on 2024-02-22 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodePalaceBase', '0004_remove_comment_name_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
