# Generated by Django 4.2.7 on 2024-02-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePalaceUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
