# Generated by Django 4.2.7 on 2024-02-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePalaceUsers', '0002_profile_bio_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
